# Generated by Django 5.2.15 on 2026-06-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorModel',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('timeout', models.IntegerField()),
                ('alert_email', models.EmailField(max_length=254)),
                ('alert_sent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('down', 'Down')], default='active')),
                ('last_beat', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
